# Gopkg.toml
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  name = "github.com/mdlayher/wifi"
  branch = "bikeos"
  source = "github.com/bikeos/wifi"

[[constraint]]
  name = "github.com/gvalkov/golang-evdev"
  branch = "master"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
